In [ ]:
import numpy as np


array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

result = []
for i in array:
  result.append(i **2)

print(result)

vectorize = array **2
print(vectorize)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256]


In [ ]:
array =np.array([10,4,53,223])
array_2d = np.array([[10,4,53,223],[10,4,53,223]])
print(array_2d)
filteredarray =array[array>20]
print(filteredarray)

sort = np.sort(array)
print(sort)

sort2d = np.sort(array_2d,axis=1)
print(sort2d)


[[ 10   4  53 223]
 [ 10   4  53 223]]
[ 53 223]
[  4  10  53 223]
[[  4  10  53 223]
 [  4  10  53 223]]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([7,8,9])

dot = np.dot(array1,array2)
print(dot)

50


In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_dot_product = np.dot(matrix1, matrix2)
print(matrix_dot_product)
# [[19 22]
#  [43 50]]

matrix = np.transpose(matrix1)
print(matrix)


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print(inverse)
# [[-2.   1. ]
#  [ 1.5 -0.5]]


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
matrix = np.array([[1, 2], [ 5, 6]])
print(matrix)

inverse = np.linalg.inv(matrix)
print(inverse)

determinant = np.linalg.det(matrix)
print(determinant)

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)



[[1 2]
 [5 6]]
[[-1.5   0.5 ]
 [ 1.25 -0.25]]
-3.999999999999999
[-0.53112887  7.53112887]
[[-0.79402877 -0.2928046 ]
 [ 0.60788018 -0.9561723 ]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

solution = np.linalg.solve(a, b)
print(solution)

[-4.   4.5]


In [ ]:
random_uniform = np.random.rand(3)  # 3 random numbers between 0 and 1
print(random_uniform)

random_normal = np.random.randn(3)  # 3 random numbers from a standard normal distribution
print(random_normal)


[0.37702275 0.32705544 0.33403526]
[0.01764442 0.74192577 1.88227526]


In [ ]:
array = np.array([10, 20, 30, 40])
random_sample = np.random.choice(array, size=2)
print(random_sample)  # Randomly selects 2 values from the array


[10 20]


In [ ]:
random_integers = np.random.randint(1, 100, size=5)  # 5 random integers between 1 and 100
print(random_integers)


[68 99 47 85  5]


In [ ]:
np.random.seed(42)
random_values = np.random.rand(3)
print(random_values)  # Always produces the same result with seed 42


[0.37454012 0.95071431 0.73199394]
