In [1]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
print(type(array_1d))

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
print(type(array_2d))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
zeros_array = np.zeros((2,3))
ones_array = np.ones((2,3))
empty_array = np.empty((2,3))
range_array = np.arange(1,100,11)
linespace_array = np.linspace(1,100,5)
print(zeros_array)
print(ones_array)
print(empty_array)
print(range_array)
print(linespace_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 1 12 23 34 45 56 67 78 89]
[  1.    25.75  50.5   75.25 100.  ]


Using Built-in Functions: NumPy provides several functions to create arrays.

np.zeros(shape): Creates an array of zeros.
np.ones(shape): Creates an array of ones.
np.arange(start, stop, step): Creates an array with a range of values.
np.linspace(start, stop, num): Creates an array of evenly spaced values between the start and stop.

In [5]:
array = np.array([[1,2,3],[4,5,6]])

print("shape:", array.shape)
print("size:", array.size)
print("ndim:", array.ndim)
print("dtype:", array.dtype)

print(array)

shape: (2, 3)
size: 6
ndim: 2
dtype: int64
[[1 2 3]
 [4 5 6]]


In [7]:
array =np.array([[1,2,3],[4,5,6]])
print(array[0])

print(array[1,2])
print(array[1:4])
array = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(array[indices])  # [10, 30, 50]


[1 2 3]
6
[[4 5 6]]
[10 30 50]


In [8]:
array = np.array([[1,2,3],[4,5,6]])
print(array.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [10]:
array =np.array([[1,2,3],[4,5,6]])
print(array.flatten())
print(array.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [14]:
array1 = np.array([1, 2])
array2 = np.array([3, 4])
combined_array = np.concatenate((array1, array2))  # [1, 2, 3, 4]


In [15]:
array = np.array([1,2,3,4,5,6])
split_array = np.array_split(array,4)
print(split_array)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [16]:
array = np.array([1, 2, 3])
print(array + 10)  # [11, 12, 13]
print(array * 2)   # [2, 4, 6]



[11 12 13]
[2 4 6]


In [18]:
array = np.array([1, 2, 3, 4])
print(np.sum(array))  # 10
print(np.mean(array))  # 2.5
print(np.min(array))  # 1
print(np.max(array))  # 4

10
2.5
1
4


In [19]:
array = np.array([1, 2, 3])
broadcasted_array = array + np.array([10])  # [11, 12, 13]
